import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import "../constants/i18n";
import I18nProvider from "@/components/I18nProvider";
const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${nunito.variable} antialiased`}>
        
      <I18nProvider>
        {children}
      </I18nProvider>
        </body>
    </html>
  );
}
